baseurl = "https://sebastianotrunfio.com/"
title = "Sebastiano Trunfio"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "sebastianotrunfio"

googleAnalytics = "UA-150816712-1"

[params]
    author = "Sebastiano Trunfio"
    info = "Sono un creator,consulente,developer,infopreneur fin dal 2008. "
    description = "Contenuti digitali, podcast e news per tutti. "
    keywords = "blog,developer,creator,consulente,infopreneur,informatico,podcast,business,lifestyle,gaming,gameplay,mcthruchannel,sebastiano,trunfio"
    avatarurl = "img/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
	
    #footercontent = "Enter a text here."

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 1
    url = "https://www.instagram.com/sebastiano.trunfio/?hl=it"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://linkedin.com/in/sebastiano-trunfio-99b256118/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/trunfio_s"
[[params.social]]
    name = "Youtube"
    icon = "fab fa-youtube fa-2x"
    weight = 4
    url = "https://youtube.com/"

# Menu links
[[menu.main]]
    name = "Articoli"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Podcast"
    weight = 2
    url = "/podcast/"
[[menu.main]]
    name = "Gameplay"
    weight = 3
    url  = "/gameplay/"
[[menu.main]]
    name = "Libri"
    weight = 4
    url  = "/libri.md/"
[[menu.main]]
    name = "Portfolio"
    weight = 5
    url  = "/portfolio.md/"